// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Conexión directa (sin pooler): la usa el CLI para migraciones.
    // La app usa DATABASE_URL (con pooler) a través del adaptador.
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
